-- AL questions from alabama-25.json
delete from public.driving_test_questions where state_code = 'AL' and source = 'drivesight-al-25';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('AL', 'Under Alabama''s Graduated Driver License (GDL) restrictions, a 16-year-old with a restricted license may not operate a vehicle between midnight and 6:00 a.m. unless accompanied by:', '["A parent, legal guardian, or licensed driver 21 or older", "Any licensed passenger over the age of 18", "A sibling who has held their license for at least one year", "A certified driver''s education instructor only"]'::jsonb, 0, 'Alabama''s GDL law prohibits 16-year-old drivers from driving between midnight and 6 a.m. unless accompanied by a parent, legal guardian, or a person 21 or older designated by the parent.', 'defensive_driving', 'hard', 'drivesight-al-25', true),
  ('AL', 'You arrive at an uncontrolled intersection at the exact same time as a vehicle to your right. Who has the legal right-of-way?', '["The vehicle on the left", "The vehicle on the right", "The vehicle traveling at a faster speed", "The larger of the two vehicles"]'::jsonb, 1, 'At uncontrolled intersections, the driver on the left must yield the right-of-way to the vehicle on the right when both arrive simultaneously.', 'right_of_way', 'medium', 'drivesight-al-25', true),
  ('AL', 'A school bus is stopped on a five-lane highway (four travel lanes and a central two-way turn lane), and its red lights are flashing. If you are traveling in the opposite direction, are you required to stop?', '["Yes, all traffic must stop regardless of direction", "No, vehicles traveling in the opposite direction may proceed", "Yes, but you may roll past at 15 mph", "No, unless the bus driver manually signals you to stop"]'::jsonb, 0, 'In Alabama, a center turn lane does not constitute a divided highway. All traffic on a multi-lane road without a physical barrier must stop for a school bus with flashing red lights.', 'school_zones', 'hard', 'drivesight-al-25', true),
  ('AL', 'For a driver under the age of 21 in Alabama, what blood alcohol concentration (BAC) threshold constitutes legal intoxication?', '["0.08% or higher", "0.05% or higher", "0.02% or higher", "Any measurable amount above 0.00%"]'::jsonb, 2, 'Alabama has a zero-tolerance law for underage drinking and driving. A BAC of 0.02% or higher is considered legally intoxicated for drivers under 21.', 'dui_alcohol_laws', 'medium', 'drivesight-al-25', true),
  ('AL', 'Heavy rain has just started to fall on a hot afternoon. Why are the roads particularly hazardous during the first 10 to 15 minutes of the storm?', '["Water levels rise rapidly in adjacent drainage ditches", "Oil and dust on the pavement mix with the rain, creating a slick surface", "Other drivers consistently speed up to reach their destinations faster", "Brake pads absorb water instantly, causing immediate brake failure"]'::jsonb, 1, 'During the initial minutes of rain, accumulated oil, dirt, and rubber dust mix with water to create an extremely slippery, soap-like layer on the road surface.', 'weather_driving', 'easy', 'drivesight-al-25', true),
  ('AL', 'When following a motorcycle on the highway, it is crucial to increase your following distance primarily because:', '["Motorcycles can stop much faster than standard passenger vehicles", "Motorcycles are legally allowed to brake test following drivers", "Motorcycles frequently stall in high-speed traffic conditions", "Motorcycles require twice the width of a standard lane to maneuver safely"]'::jsonb, 0, 'Motorcycles are lighter and can decelerate much faster than cars. Leaving extra following distance gives you adequate time to react if the motorcyclist stops suddenly.', 'motorcycle_awareness', 'medium', 'drivesight-al-25', true),
  ('AL', 'A blind pedestrian is standing at a corner waiting to cross, identifiable by a white cane. As you approach the crosswalk, your legal obligation is to:', '["Honk your horn lightly to let them know a vehicle is present", "Yield the right-of-way and come to a complete stop", "Proceed slowly through the crosswalk if they haven''t stepped off the curb yet", "Roll down your window and direct them verbally to cross safely"]'::jsonb, 1, 'Drivers must always yield the right-of-way to pedestrians carrying a white cane or using a guide dog, coming to a complete stop to ensure their safety.', 'pedestrian_safety', 'easy', 'drivesight-al-25', true),
  ('AL', 'Unless signage indicates otherwise, what is the statutory speed limit within an Alabama urban district?', '["25 mph", "30 mph", "35 mph", "45 mph"]'::jsonb, 1, 'According to Alabama''s basic speed laws, the speed limit in an urban district is 30 mph unless otherwise posted.', 'speed_limits', 'medium', 'drivesight-al-25', true),
  ('AL', 'Before pulling out to pass a slower vehicle on a two-lane country road, what sequence of actions should you take?', '["Tailgate briefly to signal your intent to the driver ahead", "Flash your high beams rapidly to clear oncoming traffic", "Check your mirrors, physically check your blind spot, and activate your turn signal", "Accelerate aggressively before moving into the oncoming lane"]'::jsonb, 2, 'Safe passing requires comprehensive awareness. You must check your mirrors for vehicles behind you, look over your shoulder to check your blind spot, and signal your intent before changing lanes.', 'passing_rules', 'easy', 'drivesight-al-25', true),
  ('AL', 'Fines for moving traffic violations committed in an active Alabama highway work zone are:', '["The same as standard violations", "Doubled when construction workers are present", "Tripled automatically", "Handled in federal court instead of state jurisdiction"]'::jsonb, 1, 'To protect highway workers, Alabama law mandates that fines for traffic violations are doubled when committed in an active construction zone with workers present.', 'work_zones', 'medium', 'drivesight-al-25', true),
  ('AL', 'You are approaching a complex intersection where the traffic signal is displaying a flashing yellow light. How should you navigate this intersection?', '["Treat it as a four-way stop and yield to the right", "Slow down, scan for cross traffic, and proceed with caution", "Come to a complete stop and wait for the light to turn solid green", "Accelerate to clear the intersection as quickly as possible"]'::jsonb, 1, 'A flashing yellow light indicates that you should slow down and proceed through the intersection with heightened caution, being prepared to yield if necessary.', 'traffic_signals', 'easy', 'drivesight-al-25', true),
  ('AL', 'While driving on I-65, you realize you have just missed your intended exit. Your safest and legal course of action is to:', '["Carefully back up on the right shoulder with your hazard lights on", "Make a U-turn through an opening in the grassy median", "Continue driving to the next available exit and turn around safely", "Stop in the right travel lane and wait for a gap to reverse"]'::jsonb, 2, 'Reversing or making U-turns on the interstate is extremely dangerous and illegal. If you miss your exit, you must always continue to the next one.', 'freeway_driving', 'easy', 'drivesight-al-25', true),
  ('AL', 'Under Alabama''s distracted driving laws, the act of writing, sending, or reading a text message while operating a motor vehicle is:', '["Permitted only for drivers over the age of 18", "Strictly illegal for all drivers on public roads", "Legal as long as the phone remains mounted on the dashboard", "Permitted only when stopped at a red traffic light"]'::jsonb, 1, 'Alabama law prohibits all drivers, regardless of age, from reading, writing, or sending a text message while operating a vehicle on a public road.', 'distracted_driving', 'easy', 'drivesight-al-25', true),
  ('AL', 'To maintain a safe following distance and avoid tailgating under ideal driving conditions, Alabama recommends utilizing:', '["The rule of one car length for every 10 mph of speed", "The ''two-second rule'' behind the vehicle in front of you", "A fixed distance of 15 feet at all times", "A distance of no less than half a mile on highways"]'::jsonb, 1, 'The ''two-second rule'' is the recommended minimum safe following distance in ideal conditions. In poor weather, this distance should be increased.', 'defensive_driving', 'medium', 'drivesight-al-25', true),
  ('AL', 'An ambulance with flashing emergency lights and an active siren is approaching rapidly from behind. Your immediate reaction should be to:', '["Maintain your current speed and lane position", "Speed up to stay ahead of the ambulance", "Pull over to the right edge of the roadway and stop completely", "Move into the left lane and slow down significantly"]'::jsonb, 2, 'When an emergency vehicle approaches with active signals, you must yield the right-of-way by pulling as close as possible to the right-hand edge of the road and stopping.', 'emergency_vehicles', 'easy', 'drivesight-al-25', true),
  ('AL', 'When approaching a railroad crossing where the warning gates have been lowered and lights are flashing, Alabama law requires you to stop within what distance of the nearest rail?', '["5 to 10 feet", "15 to 50 feet", "50 to 100 feet", "No less than 100 feet away"]'::jsonb, 1, 'You must stop between 15 and 50 feet from the nearest rail of a railroad crossing whenever a train is approaching, signals are flashing, or gates are lowered.', 'railroad_crossings', 'hard', 'drivesight-al-25', true),
  ('AL', 'You are parking your vehicle facing downhill on a steep street bordered by a physical curb. To prevent your car from rolling into traffic, your front wheels should be:', '["Positioned perfectly straight", "Turned sharply away from the curb", "Turned sharply toward the curb", "Resting directly on top of the curb edge"]'::jsonb, 2, 'When parking downhill with a curb, turning your front wheels toward the curb ensures that if the brakes fail, the vehicle will roll into the curb and stop, rather than into traffic.', 'parking', 'medium', 'drivesight-al-25', true),
  ('AL', 'Blind spots are areas around your vehicle that cannot be seen using your standard mirrors. To verify these areas are clear before executing a lane change, you must:', '["Glance briefly over your shoulder in the direction you plan to move", "Rely entirely on the panoramic view of your rearview mirror", "Tap your horn to alert vehicles that might be hiding there", "Swerve slightly to get a different mirror angle"]'::jsonb, 0, 'Mirrors leave blind spots on the left and right rear of your vehicle. The only way to ensure these areas are clear is to physically turn your head and glance over your shoulder.', 'lane_changes', 'easy', 'drivesight-al-25', true),
  ('AL', 'A solid pennant-shaped yellow sign placed strategically on the left side of a two-lane highway serves to indicate:', '["An active school crossing ahead", "The beginning of a no passing zone", "A sharp, dangerous curve to the left", "The point where a divided highway ends"]'::jsonb, 1, 'The yellow, pennant-shaped sign is exclusively used to mark a ''No Passing Zone'' and is always placed on the left side of the road facing the driver.', 'road_signs', 'medium', 'drivesight-al-25', true),
  ('AL', 'When entering a highway from a designated acceleration lane, your primary objective to ensure a safe transition should be to:', '["Stop completely at the end of the ramp and wait for an opening", "Match the speed of highway traffic and merge seamlessly when a safe gap appears", "Enter the highway at a cautious 25 mph and gradually build speed", "Merge immediately, forcing other drivers to change lanes or brake"]'::jsonb, 1, 'The acceleration lane is designed to let you build up to the speed of highway traffic before merging. Stopping or entering too slowly creates a severe collision hazard.', 'merging', 'easy', 'drivesight-al-25', true),
  ('AL', 'You are preparing to make a left turn at an intersection with a solid green light, but there is no green arrow. Oncoming traffic is approaching. What is the correct procedure?', '["Yield to oncoming traffic and execute the turn only when there is a safe gap", "Turn immediately, as the solid green light grants you the absolute right-of-way", "Pull fully into the center of the intersection and wait for the light to turn red", "Flash your high beams to alert oncoming traffic before turning in front of them"]'::jsonb, 0, 'A solid green light means you may turn left, but you must yield the right-of-way to all oncoming traffic and pedestrians. You do not have a protected turn without a green arrow.', 'intersections', 'medium', 'drivesight-al-25', true),
  ('AL', 'A continuous solid double yellow line running down the center of a two-way roadway means:', '["Passing is permitted for both directions of traffic if clear", "Passing is strictly prohibited for traffic traveling in both directions", "The lane is designated for left turns only", "Passing is allowed only during daylight hours"]'::jsonb, 1, 'Double solid yellow lines separate traffic moving in opposite directions and indicate that neither side is allowed to pass.', 'road_signs', 'easy', 'drivesight-al-25', true),
  ('AL', 'When approaching an intersection where a completely blind pedestrian is attempting to cross without a marked crosswalk, what must you do?', '["Yield the right-of-way since pedestrians have the right of way even outside marked lines", "Proceed without stopping, as crosswalk laws only apply to painted lines", "Honk repeatedly to warn them they are out of the designated zone", "Stop and physically assist them across the street"]'::jsonb, 0, 'Drivers must always yield the right-of-way to completely or partially blind pedestrians carrying a white cane or using a guide dog, regardless of whether they are in a marked crosswalk.', 'pedestrian_safety', 'hard', 'drivesight-al-25', true),
  ('AL', 'Hydroplaning occurs when a layer of water builds up between your tires and the road surface. If you feel your vehicle begin to hydroplane, you should:', '["Slam on your brakes immediately to regain traction", "Jerk the steering wheel in the opposite direction of the skid", "Ease your foot off the accelerator and steer straight until you regain control", "Accelerate slightly to push the water out from under the tires"]'::jsonb, 2, 'Braking or turning suddenly can cause you to completely lose control during hydroplaning. Easing off the gas and keeping the wheel straight allows the vehicle to naturally slow and tires to reconnect with the road.', 'weather_driving', 'medium', 'drivesight-al-25', true),
  ('AL', 'In Alabama, what is the mandatory penalty for a first-offense DUI (Driving Under the Influence) conviction?', '["A simple warning and mandatory defensive driving class", "Immediate revocation of your license for a minimum of 5 years", "A fine of $600 to $2,100 and a 90-day license suspension", "Permanent confiscation of your vehicle"]'::jsonb, 2, 'A first DUI conviction in Alabama carries severe penalties, including a $600 to $2,100 fine, up to a year in jail, and a 90-day suspension of driving privileges.', 'dui_alcohol_laws', 'hard', 'drivesight-al-25', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('AL', 'Alabama', 25)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();