-- AK questions from alaska-15.json
delete from public.driving_test_questions where state_code = 'AK' and source = 'drivesight-ak-15';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('AK', 'When driving in Alaska during the winter months, what is the most effective way to recover if your vehicle begins to skid on an icy road?', '["Slam on the brakes to engage the ABS system immediately", "Steer in the direction you want the front of the vehicle to go", "Accelerate slightly to shift weight to the rear tires", "Oversteer in the opposite direction of the skid"]'::jsonb, 1, 'If your vehicle begins to skid on ice, take your foot off the gas and carefully steer in the direction you want the front of the vehicle to go. Avoid slamming on the brakes, which can lock the wheels and make the skid worse.', 'weather_driving', 'medium', 'drivesight-ak-15', true),
  ('AK', 'Under Alaska law, studded snow tires are legally permitted on vehicles during which general timeframe?', '["Year-round for all vehicles", "Mid-September through early May", "Only during declared winter weather emergencies", "November 1st through March 1st"]'::jsonb, 1, 'Studded tires are legally allowed in Alaska from September 15th to May 1st (or May 15th for areas north of 60 degrees North Latitude) to prevent severe damage to paved roads during warmer months.', 'weather_driving', 'hard', 'drivesight-ak-15', true),
  ('AK', 'You are driving on a rural Alaskan highway and spot a moose standing near the shoulder. What is the safest course of action?', '["Honk your horn continuously to scare it away", "Maintain your speed and swerve into the oncoming lane to pass", "Slow down significantly and be prepared to stop", "Flash your high beams rapidly to blind the animal"]'::jsonb, 2, 'Moose are unpredictable and top-heavy. Striking one can be fatal for the occupants of the vehicle. You should always slow down and prepare to stop if you see wildlife near the roadway.', 'defensive_driving', 'easy', 'drivesight-ak-15', true),
  ('AK', 'Unless otherwise posted by road signs, what is the maximum statutory speed limit on Alaskan state highways?', '["45 mph", "55 mph", "65 mph", "75 mph"]'::jsonb, 1, 'The maximum speed limit on state highways in Alaska is 55 mph unless signs specifically indicate a higher speed limit, such as 65 mph on certain interstates.', 'speed_limits', 'medium', 'drivesight-ak-15', true),
  ('AK', 'Alaska''s ''Implied Consent'' law means that by operating a motor vehicle on public roads, you automatically agree to:', '["Allow police to search your vehicle without a warrant at any time", "Submit to a chemical test for alcohol or drugs if lawfully arrested for DUI", "Pay all traffic fines within 30 days of receiving a citation", "Carry liability insurance for any passengers in your car"]'::jsonb, 1, 'Implied consent means that if you are arrested for driving under the influence, you have already consented to take a breath or blood test to determine your blood alcohol concentration.', 'dui_alcohol_laws', 'hard', 'drivesight-ak-15', true),
  ('AK', 'You are approaching a stopped school bus with its red lights flashing on an undivided two-lane road in Anchorage. What are you legally required to do?', '["Slow down to 15 mph and pass with caution", "Stop only if children are actively crossing the street", "Stop completely and wait until the red lights stop flashing", "Honk your horn before pulling around the left side of the bus"]'::jsonb, 2, 'On an undivided roadway, all traffic traveling in both directions must come to a complete stop for a school bus with flashing red lights and an extended stop arm.', 'school_zones', 'easy', 'drivesight-ak-15', true),
  ('AK', 'In Alaska, the act of reading or typing a text message while operating a moving motor vehicle is considered:', '["A minor traffic infraction resulting in a warning", "Legal as long as the phone is held below the steering wheel", "A serious misdemeanor crime that carries strict penalties", "Only illegal for drivers under the age of 21"]'::jsonb, 2, 'Alaska has some of the strictest distracted driving laws in the country. Texting while driving is a misdemeanor offense, not just a traffic ticket, and carries severe fines.', 'distracted_driving', 'medium', 'drivesight-ak-15', true),
  ('AK', 'An emergency vehicle with flashing lights and an active siren is approaching from behind on a two-lane road. You must:', '["Maintain your speed until you find a designated pull-out area", "Pull over to the right edge of the roadway and stop completely", "Move to the left lane to give them room to pass on the right", "Accelerate to stay ahead of the emergency vehicle"]'::jsonb, 1, 'When an emergency vehicle is approaching with lights and sirens, you must immediately yield the right-of-way by pulling as far to the right as possible and coming to a complete stop.', 'emergency_vehicles', 'easy', 'drivesight-ak-15', true),
  ('AK', 'Alaska law requires drivers to turn on their vehicle''s headlights during which specific times?', '["Only when driving on unpaved or gravel roads", "From a half-hour after sunset to a half-hour before sunrise", "Whenever the vehicle is traveling over 45 mph", "Only between the hours of 10:00 PM and 4:00 AM"]'::jsonb, 1, 'Headlights must be used from a half-hour after sunset until a half-hour before sunrise, or at any other time when visibility is limited and you cannot see clearly for 1,000 feet.', 'weather_driving', 'medium', 'drivesight-ak-15', true),
  ('AK', 'When parking your vehicle facing uphill on a street with a defined physical curb, which way should you turn your front steering wheels?', '["Straight ahead to keep the steering column locked", "Sharply toward the curb", "Sharply away from the curb", "Parallel to the centerline of the road"]'::jsonb, 2, 'When parking uphill with a curb, turn your wheels away from the curb. If the brakes fail, the vehicle will roll backward, and the back of the front tire will catch the curb, stopping the car.', 'parking', 'medium', 'drivesight-ak-15', true),
  ('AK', 'When driving behind an active snowplow clearing an Alaskan highway, what is the safest and recommended procedure?', '["Pass the snowplow quickly on the right shoulder", "Tailgate the plow closely to take advantage of the cleared track", "Stay at least 200 feet behind and avoid passing unless absolutely necessary", "Flash your high beams until the plow pulls over to let you pass"]'::jsonb, 2, 'Snowplows create whiteout conditions and drop anti-icing chemicals. You should maintain a safe following distance of at least 200 feet and never attempt to pass an active plow.', 'passing_rules', 'hard', 'drivesight-ak-15', true),
  ('AK', 'When preparing to enter a multi-lane roundabout intersection, which vehicles have the legal right-of-way?', '["Vehicles entering from the right", "Traffic already circulating inside the roundabout", "Commercial trucks and large SUVs", "Vehicles attempting to exit the roundabout"]'::jsonb, 1, 'Drivers entering a roundabout must always yield the right-of-way to vehicles, bicyclists, and pedestrians already circulating inside the roundabout.', 'intersections', 'medium', 'drivesight-ak-15', true),
  ('AK', 'A continuous solid double yellow line running down the center of the roadway indicates that:', '["Passing is permitted only for the lane with a broken line", "The lane is designated for left turns and U-turns only", "Passing is strictly prohibited for traffic traveling in both directions", "You are entering a designated school zone"]'::jsonb, 2, 'A solid double yellow line separates traffic moving in opposite directions. Neither side is permitted to cross the double lines to pass another vehicle.', 'lane_changes', 'easy', 'drivesight-ak-15', true),
  ('AK', 'Under ideal dry conditions, the recommended following distance is two seconds. On packed snow or icy roads, you should increase this distance to at least:', '["3 to 4 seconds", "8 to 10 seconds", "15 to 20 seconds", "One full mile"]'::jsonb, 1, 'Stopping distances increase exponentially on ice and snow. You should increase your following distance to at least 8 to 10 seconds to allow for safe reaction and braking time.', 'defensive_driving', 'medium', 'drivesight-ak-15', true),
  ('AK', 'When approaching a railroad crossing where the warning gates have been lowered and red lights are flashing, you must stop your vehicle:', '["Directly on the tracks to wait for the train", "Between 15 and 50 feet from the nearest rail", "At least 100 feet away from the crossing", "Only if you can physically see the train approaching"]'::jsonb, 1, 'State law requires drivers to stop between 15 and 50 feet from the nearest rail at a railroad crossing when flashing red lights, lowered gates, or a flagger warn of an approaching train.', 'railroad_crossings', 'hard', 'drivesight-ak-15', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('AK', 'Alaska', 15)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();