-- AZ questions from arizona-12.json
delete from public.driving_test_questions where state_code = 'AZ' and source = 'drivesight-az-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('AZ', 'You are driving on an Arizona highway and suddenly encounter a dense dust storm (haboob) that drops visibility to zero. What is the safest and legally recommended course of action?', '["Turn on your hazard lights and slow down to 15 mph", "Pull completely off the pavement, turn off all lights, and take your foot off the brake", "Stop immediately in your travel lane and activate your high beams", "Maintain your speed but sound your horn continuously until you exit the storm"]'::jsonb, 1, 'In an Arizona dust storm, you must pull completely off the roadway, turn off all vehicle lights (including hazard lights), set the emergency brake, and take your foot off the brake pedal so other drivers don''t follow your tail lights and rear-end you.', 'weather_driving', 'hard', 'drivesight-az-12', true),
  ('AZ', 'In Arizona, driving across the ''gore area'' on a freeway is illegal and heavily fined. What is the gore area?', '["The designated emergency pull-off zone on steep mountain grades", "The far-left High Occupancy Vehicle (HOV) lane during restricted hours", "The painted triangular space between a highway travel lane and an exit/entrance ramp", "The unpaved dirt shoulder on the right side of the interstate"]'::jsonb, 2, 'The gore area is the triangular painted area between a freeway and an exit or entrance ramp. Crossing over this solid white V-shaped area is dangerous and strictly prohibited in Arizona.', 'freeway_driving', 'medium', 'drivesight-az-12', true),
  ('AZ', 'Under Arizona''s Graduated Driver License laws, a teen with a Class G license is restricted from driving between what hours during their first six months, unless accompanied by a parent or guardian?', '["10:00 PM and 5:00 AM", "Midnight and 5:00 AM", "11:00 PM and 6:00 AM", "9:00 PM and 6:00 AM"]'::jsonb, 1, 'During the first six months of holding a Class G graduated license in Arizona, a teen may not drive between midnight and 5:00 a.m. unless accompanied by a parent, legal guardian, or a certified driving instructor.', 'defensive_driving', 'hard', 'drivesight-az-12', true),
  ('AZ', 'When approaching a standard school crossing zone in Arizona, the mandated speed limit is:', '["15 mph", "20 mph", "25 mph", "10 mph"]'::jsonb, 0, 'The speed limit approaching a school crosswalk in Arizona is 15 mph. You must adhere to this limit whenever the yellow crosswalk signs are displayed or flashing.', 'school_zones', 'easy', 'drivesight-az-12', true),
  ('AZ', 'Arizona law categorizes a DUI as an ''Extreme DUI'' when a driver''s Blood Alcohol Concentration (BAC) reaches or exceeds:', '["0.08%", "0.10%", "0.15%", "0.20%"]'::jsonb, 2, 'While standard DUI in Arizona is 0.08%, an ''Extreme DUI'' is charged when a driver has a BAC of 0.15% or higher, which carries significantly harsher jail times and fines.', 'dui_alcohol_laws', 'medium', 'drivesight-az-12', true),
  ('AZ', 'You are driving on a two-lane road and a vehicle behind you is tailgating aggressively, flashing their lights to pass. What is the best defensive driving technique?', '["Tap your brakes rapidly to warn them to back off", "Accelerate to match the speed they wish to travel", "Move slightly to the right side of your lane and let them pass", "Turn on your hazard lights and stay in the center of your lane"]'::jsonb, 2, 'If someone is tailgating you and wants to pass, you should move slightly to the right side of your lane and avoid speeding up, allowing them to pass safely and reducing the danger to yourself.', 'defensive_driving', 'easy', 'drivesight-az-12', true),
  ('AZ', 'In Arizona, the ''Move Over'' law requires drivers approaching a stationary emergency vehicle with flashing lights on a multi-lane highway to:', '["Stop completely until an officer signals you to proceed", "Move into a lane that is not immediately adjacent to the emergency vehicle", "Honk your horn to acknowledge their presence and maintain speed", "Accelerate past the incident quickly to clear the area"]'::jsonb, 1, 'Arizona''s Move Over law mandates that you shift over one lane away from any stationary emergency, maintenance, or stranded vehicle with flashing lights. If you cannot move over safely, you must significantly reduce your speed.', 'emergency_vehicles', 'medium', 'drivesight-az-12', true),
  ('AZ', 'Unless otherwise posted by road signs, what is the speed limit in an Arizona business or residential district?', '["20 mph", "25 mph", "30 mph", "35 mph"]'::jsonb, 1, 'According to Arizona''s basic speed law, the maximum speed in residential and business districts is 25 mph unless a different speed is posted.', 'speed_limits', 'easy', 'drivesight-az-12', true),
  ('AZ', 'You are preparing to make a right turn at a red light. After coming to a complete stop, you notice a pedestrian stepping into the crosswalk. Who has the right-of-way?', '["You have the right-of-way because you are turning", "The pedestrian has the right-of-way and you must wait until they cross safely", "Whoever entered the intersection first has the right-of-way", "You may proceed if you can squeeze past the pedestrian without hitting them"]'::jsonb, 1, 'Even when making a legal right turn on red, you must yield the right-of-way to all pedestrians crossing in the intersection.', 'pedestrian_safety', 'easy', 'drivesight-az-12', true),
  ('AZ', 'Under the ''Stupid Motorist Law'' in Arizona, you may be held financially responsible for the cost of your own rescue if you:', '["Run out of gas on a rural interstate highway", "Deliberately drive past barricades into a flooded wash or roadway", "Fail to carry a spare tire and require a tow truck", "Drive off a mountain road due to excessive speeding"]'::jsonb, 1, 'Arizona''s ''Stupid Motorist Law'' states that any driver who bypasses barricades to enter a flooded stretch of roadway and requires emergency extraction can be billed for the cost of the rescue operations.', 'weather_driving', 'medium', 'drivesight-az-12', true),
  ('AZ', 'A solid yellow line next to a broken yellow line down the center of the road indicates that passing is:', '["Prohibited for vehicles traveling in both directions", "Permitted for vehicles adjacent to the solid line", "Permitted for vehicles adjacent to the broken line", "Permitted only for motorcycles and emergency vehicles"]'::jsonb, 2, 'When there is a solid yellow line next to a broken yellow line, passing is only permitted for the drivers traveling on the side with the broken line, provided the way is clear.', 'passing_rules', 'easy', 'drivesight-az-12', true),
  ('AZ', 'When sharing the road with a commercial semi-truck, what is the most dangerous area around the truck, often referred to as the ''No-Zone''?', '["Directly in front of the truck''s grill", "Directly behind the truck''s trailer", "The blind spots on the sides, rear, and front of the truck", "The lane to the far left of the truck"]'::jsonb, 2, 'The ''No-Zone'' refers to the large blind spots located immediately in front of, behind, and along the sides of commercial trucks. If you cannot see the truck''s mirrors, the driver cannot see you.', 'defensive_driving', 'medium', 'drivesight-az-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('AZ', 'Arizona', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();