-- AR questions from arkansas-10.json
delete from public.driving_test_questions where state_code = 'AR' and source = 'drivesight-ar-10';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('AR', 'Under Arkansas law, a driver must automatically turn on their vehicle''s headlights whenever:', '["Driving over the speed of 55 mph", "The vehicle''s windshield wipers are in use due to weather", "Entering any marked construction or work zone", "Driving on an unpaved county road"]'::jsonb, 1, 'Arkansas law requires that a driver turn on their headlights whenever their windshield wipers are in use to clear rain, snow, or other precipitation.', 'weather_driving', 'easy', 'drivesight-ar-10', true),
  ('AR', 'On a multi-lane highway in Arkansas, the far left lane is legally designated for:', '["Vehicles traveling exactly at the posted speed limit", "Commercial semi-trucks and buses only", "Passing slower traffic and preparing for left turns", "Drivers utilizing cruise control systems"]'::jsonb, 2, 'Arkansas enforces a ''keep right'' law. The left lane on multi-lane highways is legally intended only for passing slower vehicles or preparing to make a left turn.', 'lane_changes', 'medium', 'drivesight-ar-10', true),
  ('AR', 'You are driving on an Arkansas highway divided by a 20-foot wide grass median. A school bus traveling in the opposite direction has stopped with its red lights flashing. What must you do?', '["Come to a complete stop and wait for the lights to turn off", "Slow to 15 mph and proceed cautiously past the bus", "You are not required to stop because the highway is divided by a median", "Stop only if children are actively crossing the grass median"]'::jsonb, 2, 'In Arkansas, if a highway is divided by a physical barrier or an unpaved median strip at least 20 feet wide, drivers traveling in the opposite direction of a stopped school bus do not have to stop.', 'school_zones', 'hard', 'drivesight-ar-10', true),
  ('AR', 'In Arkansas, ''Paul''s Law'' severely restricts distracted driving. Which of the following is true regarding cell phone use while driving?', '["Texting is illegal for all drivers, regardless of age", "Drivers over 21 may text if stopped at a red light", "Drivers ages 18-20 may use a handheld phone for any reason", "Only drivers with a learner''s permit are banned from texting"]'::jsonb, 0, 'Under ''Paul''s Law'' in Arkansas, writing, typing, reading, or sending text messages on a wireless device is strictly illegal for all drivers, regardless of age or experience level.', 'distracted_driving', 'easy', 'drivesight-ar-10', true),
  ('AR', 'When approaching a flashing red traffic light at an intersection, your legal obligation is to:', '["Slow down and yield to cross traffic without coming to a full stop", "Treat the signal as a stop sign, stopping completely before proceeding safely", "Treat the signal as a yield sign, only stopping if pedestrians are present", "Wait until the light turns solid green to proceed"]'::jsonb, 1, 'A flashing red traffic light has the exact same legal meaning as a stop sign. You must come to a complete stop, yield the right-of-way, and proceed only when it is safe to do so.', 'traffic_signals', 'easy', 'drivesight-ar-10', true),
  ('AR', 'According to Arkansas laws regarding railroad crossings, a driver must stop their vehicle within what distance from the nearest track when a train is approaching?', '["No closer than 5 feet and no further than 20 feet", "No closer than 15 feet and no further than 50 feet", "Exactly 30 feet from the nearest rail", "Only behind the solid white stop line"]'::jsonb, 1, 'When approaching a railroad crossing with active warnings or a visible train, Arkansas law requires you to stop within 50 feet, but no less than 15 feet, from the nearest rail.', 'railroad_crossings', 'medium', 'drivesight-ar-10', true),
  ('AR', 'You are driving on an unpaved county dirt road and approach an intersection with a paved state highway. Who has the right-of-way?', '["The vehicle on the unpaved road", "The vehicle on the paved state highway", "The vehicle that arrives at the intersection first", "The vehicle making a right turn"]'::jsonb, 1, 'When entering a paved thoroughfare from an unpaved dirt or gravel road, the vehicle entering from the unpaved road must yield the right-of-way to traffic on the paved road.', 'right_of_way', 'medium', 'drivesight-ar-10', true),
  ('AR', 'For drivers under the legal drinking age of 21 in Arkansas, the state''s ''Zero Tolerance'' law considers it illegal to drive with a Blood Alcohol Concentration (BAC) of:', '["0.08% or higher", "0.05% or higher", "0.02% or higher", "0.10% or higher"]'::jsonb, 2, 'Arkansas has a strict Zero Tolerance law for underage drinking and driving. A BAC of 0.02% or greater is grounds for an underage DUI charge.', 'dui_alcohol_laws', 'hard', 'drivesight-ar-10', true),
  ('AR', 'When parallel parking your vehicle along an Arkansas street, your wheels must be positioned:', '["More than 24 inches from the right curb", "Resting directly on top of the curb line", "No more than 18 inches from the right curb", "Turned sharply to the left at all times"]'::jsonb, 2, 'To properly parallel park and ensure you are not obstructing traffic, your vehicle''s wheels must be positioned parallel to and no more than 18 inches from the curb.', 'parking', 'medium', 'drivesight-ar-10', true),
  ('AR', 'A solid white line separating traffic traveling in the same direction signifies that:', '["Lane changes are encouraged to pass slower traffic", "The lane is designated for High Occupancy Vehicles (HOV)", "Lane changes are discouraged, and you should stay in your lane", "You are entering a designated school zone"]'::jsonb, 2, 'While broken white lines allow passing, a solid white line between lanes of traffic moving in the same direction indicates that lane changes are hazardous and strongly discouraged.', 'road_signs', 'easy', 'drivesight-ar-10', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('AR', 'Arkansas', 10)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();