-- CO questions from colorado-12.json
delete from public.driving_test_questions where state_code = 'CO' and source = 'drivesight-co-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('CO', 'To control your vehicle''s speed and prevent severe brake fade while descending a steep mountain grade in Colorado, your safest mechanical action is to:', '["Pump the brake pedal vigorously all the way down the mountain", "Shift your transmission into a lower gear", "Turn the engine off and coast in neutral", "Apply the emergency parking brake lightly"]'::jsonb, 1, 'Riding your brakes down a steep grade can cause them to overheat and fail. Shifting to a lower gear allows the engine''s compression to safely control your descent speed.', 'weather_driving', 'medium', 'drivesight-co-12', true),
  ('CO', 'In Colorado, law enforcement can charge a driver with Driving While Ability Impaired (DWAI), a lesser but serious alcohol offense, with a Blood Alcohol Concentration (BAC) as low as:', '["0.02%", "0.04%", "0.05%", "0.08%"]'::jsonb, 2, 'While standard DUI is 0.08%, Colorado law includes a DWAI charge. If your BAC is between 0.05% and 0.079%, you can be arrested for Driving While Ability Impaired.', 'dui_alcohol_laws', 'hard', 'drivesight-co-12', true),
  ('CO', 'Under Colorado''s Move Over Law, if you approach a stationary emergency vehicle or tow truck with flashing lights and traffic prevents you from safely changing lanes, you must:', '["Stop completely in your lane and wait for directions", "Maintain your speed but honk to alert the workers of your presence", "Reduce your speed to at least 20 mph below the posted speed limit", "Accelerate to clear the dangerous area quickly"]'::jsonb, 2, 'If you cannot safely shift one lane away from a stationary emergency or maintenance vehicle in Colorado, the law requires you to reduce your speed to at least 20 mph below the posted limit.', 'emergency_vehicles', 'medium', 'drivesight-co-12', true),
  ('CO', 'During severe winter snowstorms, the Colorado Department of Transportation may implement a Passenger Vehicle Traction Law (Code 15). What does this mandate for motorists?', '["All vehicles are banned from the highway except snowplows", "Vehicles must have snow tires, M+S rated tires, or carry traction devices like chains or AutoSocks", "Only four-wheel-drive (4WD) vehicles are permitted on mountain passes", "All passenger vehicles must follow behind a state pilot car"]'::jsonb, 1, 'Under a Code 15 Traction Law, all motorists must have either 4WD/AWD, snow tires, tires with the mud/snow (M+S) designation, or carry alternative traction devices like chains or AutoSocks.', 'weather_driving', 'hard', 'drivesight-co-12', true),
  ('CO', 'When approaching a multi-lane roundabout intersection in Colorado, which vehicles hold the legal right-of-way?', '["The larger, heavier commercial vehicles", "Traffic attempting to enter the roundabout from the right", "Traffic that is already circulating inside the roundabout", "Vehicles attempting to exit the roundabout"]'::jsonb, 2, 'Drivers entering a roundabout must always yield the right-of-way to vehicles, bicyclists, and pedestrians already circulating inside the traffic circle.', 'intersections', 'easy', 'drivesight-co-12', true),
  ('CO', 'When a school bus stops and activates its flashing red lights and stop arm on a standard two-lane Colorado road, drivers approaching from both directions must stop at least:', '["10 feet away", "20 feet away", "50 feet away", "100 feet away"]'::jsonb, 1, 'Colorado law requires that vehicles approaching from any direction must stop at least 20 feet away from a school bus displaying flashing red lights and an extended stop signal arm.', 'school_zones', 'medium', 'drivesight-co-12', true),
  ('CO', 'According to Colorado state law, what are the restrictions regarding cell phone use for drivers who are under the age of 18?', '["They may use a cell phone only if it is completely hands-free", "They may send text messages while stopped at a red traffic light", "They are strictly prohibited from using a cell phone for any reason, except to contact emergency services", "They may use a handheld phone if a parent is in the passenger seat"]'::jsonb, 2, 'Drivers under 18 in Colorado are prohibited from using a mobile phone while driving for any reason, including hands-free devices, unless they are contacting the police or fire department in an emergency.', 'distracted_driving', 'easy', 'drivesight-co-12', true),
  ('CO', 'Unless otherwise posted by signage, what is the maximum statutory speed limit on narrow, winding mountain highways and blind curves in Colorado?', '["15 mph", "20 mph", "25 mph", "35 mph"]'::jsonb, 1, 'Due to the treacherous nature of the terrain, Colorado sets the baseline maximum speed limit on narrow, winding mountain highways and blind curves at 20 mph.', 'speed_limits', 'hard', 'drivesight-co-12', true),
  ('CO', 'You are driving on a multi-lane Colorado highway and a motorcyclist is traveling in your lane ahead of you. Are you legally permitted to share the same lane side-by-side with the motorcycle?', '["Yes, if the lane is wide enough to accommodate both comfortably", "Yes, but only during daylight hours", "No, a passenger vehicle may never share a lane with a motorcycle", "No, unless the motorcyclist motions for you to pull up next to them"]'::jsonb, 2, 'Motorcycles are entitled to the full width of a traffic lane. While two motorcycles may share a single lane side-by-side, a passenger car is strictly prohibited from sharing a lane with a motorcycle.', 'motorcycle_awareness', 'medium', 'drivesight-co-12', true),
  ('CO', 'You are parallel parking your vehicle facing downhill on a steep mountain street that does not have a physical curb. To secure the vehicle safely, which way should you turn your front wheels?', '["Perfectly straight ahead", "Sharply to the left (toward the center of the road)", "Sharply to the right (toward the shoulder or edge of the road)", "It does not matter as long as the emergency brake is fully engaged"]'::jsonb, 2, 'When parking downhill without a curb, always turn your wheels sharply to the right. If the brakes fail, the vehicle will roll off the roadway into the shoulder/dirt rather than into oncoming traffic.', 'parking', 'easy', 'drivesight-co-12', true),
  ('CO', 'When passing a bicyclist who is traveling in the same direction on a Colorado roadway, state law mandates that a motor vehicle must leave a minimum physical clearance of at least:', '["2 feet", "3 feet", "5 feet", "One full traffic lane"]'::jsonb, 1, 'Colorado law requires motorists to give bicyclists at least 3 feet of space between the widest part of their vehicle and the widest part of the bicyclist when passing.', 'passing_rules', 'medium', 'drivesight-co-12', true),
  ('CO', 'As you travel down an entrance ramp to merge onto I-25 in Colorado, your primary responsibility as the merging driver is to:', '["Force highway traffic to change lanes by signaling aggressively", "Drive to the very end of the ramp and come to a complete stop to check for traffic", "Accelerate to match the speed of freeway traffic and yield to vehicles already on the highway", "Cross the solid white line early to merge as quickly as possible"]'::jsonb, 2, 'The vehicle entering the freeway must yield the right-of-way. You should use the acceleration lane to match the speed of highway traffic and merge seamlessly when a safe gap appears.', 'merging', 'easy', 'drivesight-co-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('CO', 'Colorado', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();