-- CT questions from connecticut-12.json
delete from public.driving_test_questions where state_code = 'CT' and source = 'drivesight-ct-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('CT', 'Under Connecticut law, what are the restrictions regarding mobile phone use for drivers who are 16 or 17 years old?', '["They may use a hands-free device as long as the phone remains mounted", "They are completely prohibited from using any mobile electronic device, even if it is hands-free", "They may send text messages only when completely stopped at a traffic light", "They may use a handheld phone only to check GPS directions"]'::jsonb, 1, 'Connecticut has strict distracted driving laws for minors. Drivers under the age of 18 are prohibited from using any mobile electronic device, whether handheld or hands-free, except in the case of a genuine emergency.', 'distracted_driving', 'medium', 'drivesight-ct-12', true),
  ('CT', 'Connecticut enforces a Zero-Tolerance law for underage drinking and driving. A 16- or 17-year-old driver will face an administrative license suspension if they drive with an elevated Blood Alcohol Content (BAC) of at least:', '["0.01%", "0.02%", "0.05%", "0.08%"]'::jsonb, 1, 'Under Connecticut''s Zero-Tolerance law, a 16- or 17-year-old driver will have their license suspended for at least one year if they are found driving with a BAC equal to or greater than 0.02%.', 'dui_alcohol_laws', 'hard', 'drivesight-ct-12', true),
  ('CT', 'In Connecticut, state law requires you to turn on your vehicle''s headlights whenever:', '["You are driving on an interstate highway", "Your vehicle''s windshield wipers are in continuous use due to weather conditions", "The temperature drops below freezing", "You enter any marked construction zone"]'::jsonb, 1, 'Connecticut law requires drivers to activate their headlights whenever their windshield wipers are in continuous use to clear rain, snow, or other precipitation, ensuring better visibility for everyone on the road.', 'weather_driving', 'easy', 'drivesight-ct-12', true),
  ('CT', 'When approaching a stationary emergency vehicle or tow truck displaying flashing lights on a multi-lane Connecticut highway, the state''s ''Move Over'' law requires you to:', '["Maintain your speed but honk your horn to alert them of your presence", "Reduce your speed significantly and move over one lane away from the stationary vehicle, if safe to do so", "Stop completely in your lane and wait for an officer to wave you around", "Accelerate to pass the hazard as quickly as possible"]'::jsonb, 1, 'The Move Over law protects roadside workers and emergency responders. If you cannot safely move over a lane, you must slow down to a reasonable and safe speed below the posted limit.', 'emergency_vehicles', 'medium', 'drivesight-ct-12', true),
  ('CT', 'You are parking your vehicle facing uphill on a street that has a raised physical curb. To ensure the vehicle doesn''t roll into traffic if the brakes fail, your front wheels should be:', '["Kept perfectly straight", "Turned sharply toward the curb", "Turned sharply away from the curb", "Resting directly on top of the curb"]'::jsonb, 2, 'When parked facing uphill next to a curb, turning the steering wheel away from the curb ensures that if the vehicle begins to roll backward, the back of the front tire will hit the curb and stop the vehicle.', 'parking', 'medium', 'drivesight-ct-12', true),
  ('CT', 'A school bus is stopped ahead of you on an undivided two-lane road in Connecticut, and its red lights are actively flashing. What is your legal obligation?', '["You must come to a complete stop at least 10 feet away and remain stopped until the red lights turn off", "You may proceed at 15 mph if no children are actively in the crosswalk", "Only traffic traveling in the same direction as the bus is required to stop", "You must honk your horn to warn children before passing the bus carefully"]'::jsonb, 0, 'In Connecticut, drivers approaching a stopped school bus with flashing red lights from either direction on an undivided highway must stop at least 10 feet away to allow children to cross safely.', 'school_zones', 'easy', 'drivesight-ct-12', true),
  ('CT', 'When passing a bicyclist traveling in the same direction on a Connecticut roadway, a motorist must leave a minimum safe passing distance of at least:', '["1 foot", "2 feet", "3 feet", "5 feet"]'::jsonb, 2, 'Connecticut''s safe passing law mandates that drivers must provide at least 3 feet of physical clearance when passing a bicyclist on the road.', 'passing_rules', 'medium', 'drivesight-ct-12', true),
  ('CT', 'You arrive at an uncontrolled intersection at the exact same time as another passenger vehicle located on your right. Who holds the legal right-of-way?', '["You, because you are on the left", "The vehicle on the right", "Whichever vehicle is larger", "The vehicle traveling at a faster speed"]'::jsonb, 1, 'At an uncontrolled intersection, the fundamental right-of-way rule dictates that the vehicle on the left must yield to the vehicle on the right when both arrive at the same time.', 'right_of_way', 'easy', 'drivesight-ct-12', true),
  ('CT', 'To maintain a safe following distance under normal driving conditions, Connecticut recommends that drivers utilize the:', '["One car length rule for every 10 mph of speed", "Two-second rule", "Three-second rule", "Five-second rule"]'::jsonb, 2, 'The three-second rule is the recommended safe following distance in Connecticut under ideal conditions. This should be increased during inclement weather or when following large trucks or motorcycles.', 'defensive_driving', 'easy', 'drivesight-ct-12', true),
  ('CT', 'When you approach a crosswalk and notice a pedestrian carrying a white cane or accompanied by a guide dog, you must:', '["Tap your horn gently to alert them to your presence", "Slow down and proceed around them cautiously", "Yield the right-of-way and come to a complete stop", "Roll down your window and give verbal directions"]'::jsonb, 2, 'Drivers must always yield the right-of-way and come to a complete stop for pedestrians who are blind or visually impaired, identified by a white cane or a guide dog.', 'pedestrian_safety', 'easy', 'drivesight-ct-12', true),
  ('CT', 'When utilizing an acceleration lane to enter a Connecticut highway, your primary goal should be to:', '["Drive to the end of the lane and stop completely to look for a gap", "Match the speed of highway traffic and merge smoothly when a safe gap appears", "Force highway drivers to change lanes by signaling aggressively", "Enter the highway at a cautious 30 mph"]'::jsonb, 1, 'The acceleration lane is designed to allow entering vehicles to build their speed to match the flow of highway traffic, making merging seamless and safe.', 'merging', 'medium', 'drivesight-ct-12', true),
  ('CT', 'You approach an intersection displaying a flashing red traffic signal. How should you treat this light under Connecticut law?', '["The same as a yield sign, slowing down and proceeding if clear", "The same as a stop sign, coming to a complete stop before proceeding safely", "You must stop and wait for the light to turn solid green", "Proceed with caution without stopping, as you have the right-of-way"]'::jsonb, 1, 'A flashing red traffic light carries the exact same legal meaning as a stop sign. You must come to a complete stop, yield to cross traffic and pedestrians, and proceed only when clear.', 'traffic_signals', 'easy', 'drivesight-ct-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('CT', 'Connecticut', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();