-- FL questions from florida-11.json
delete from public.driving_test_questions where state_code = 'FL' and source = 'drivesight-fl-11';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('FL', 'Under Florida''s Move Over law, if you approach a stationary emergency vehicle, tow truck, or sanitation vehicle with flashing lights on a multi-lane highway and cannot safely shift over a lane, you are legally required to:', '["Come to a complete stop in your lane and wait for the vehicle to move", "Slow down to a speed that is 20 mph less than the posted speed limit", "Maintain your speed but sound your horn to alert workers of your presence", "Accelerate quickly to pass the hazard and clear the traffic backup"]'::jsonb, 1, 'Florida''s Move Over law requires that if you cannot safely vacate the lane closest to an emergency or service vehicle, you must slow down to 20 mph below the posted speed limit. If the speed limit is 20 mph or less, you must slow down to 5 mph.', 'emergency_vehicles', 'medium', 'drivesight-fl-11', true),
  ('FL', 'Florida law explicitly requires you to turn on your vehicle''s headlights under which of the following specific weather-related conditions?', '["Whenever the temperature drops below 40 degrees Fahrenheit", "Whenever you are driving on a rural unpaved road", "Whenever your windshield wipers are activated due to rain or other precipitation", "Only when visibility is completely reduced to zero during a hurricane"]'::jsonb, 2, 'In Florida, state law strictly mandates that your headlights must be turned on whenever your windshield wipers are in use to clear rain, fog, or other precipitation.', 'weather_driving', 'easy', 'drivesight-fl-11', true),
  ('FL', 'According to Florida''s Graduated Driver License (GDL) rules, a 16-year-old licensed driver may NOT operate a vehicle during which hours, unless accompanied by a licensed driver 21 or older or driving to/from work?', '["Between 9:00 PM and 5:00 AM", "Between 11:00 PM and 6:00 AM", "Between Midnight and 6:00 AM", "Between 10:00 PM and 4:00 AM"]'::jsonb, 1, 'To protect young drivers, Florida restricts 16-year-old drivers from operating a motor vehicle between 11:00 PM and 6:00 AM unless they are driving directly to or from work, or are accompanied by a licensed driver who is at least 21 years old.', 'defensive_driving', 'hard', 'drivesight-fl-11', true),
  ('FL', 'You are driving on a Florida highway divided by a raised, five-foot concrete barrier. A school bus traveling in the opposite direction has stopped and extended its flashing red stop arm. What is your legal obligation?', '["You must come to a complete stop and remain stopped until the lights turn off", "You must slow down to 15 mph and pass with extreme caution", "You are not required to stop because the highway is separated by a physical barrier", "You must sound your horn to warn crossing children but may maintain your speed"]'::jsonb, 2, 'If a highway is divided by a raised barrier or an unpaved median at least five feet wide, drivers traveling in the opposite direction of a stopped school bus do not have to stop.', 'school_zones', 'medium', 'drivesight-fl-11', true),
  ('FL', 'Under Florida''s Zero Tolerance law, a driver under the age of 21 will face an automatic six-month license suspension if they are caught driving with a Blood Alcohol Level (BAL) of at least:', '["0.02%", "0.04%", "0.06%", "0.08%"]'::jsonb, 0, 'Florida enforces a strict Zero Tolerance policy for underage drinking. Any driver under 21 who is stopped and has a BAL of 0.02% or higher will automatically have their driving privilege suspended for six months.', 'dui_alcohol_laws', 'medium', 'drivesight-fl-11', true),
  ('FL', 'What is the specific penalty enhancement for committing a moving speed violation within an active Florida highway construction zone where workers are visibly present?', '["The violator''s license is immediately suspended for 30 days", "The standard fine for the speeding violation is automatically doubled", "The driver must perform 40 hours of community service", "The driver''s vehicle is subject to impoundment"]'::jsonb, 1, 'To protect highway workers, Florida law requires that fines for speeding violations be doubled when the offense occurs in a posted construction or work zone and workers are present.', 'work_zones', 'easy', 'drivesight-fl-11', true),
  ('FL', 'When parking your vehicle facing downhill on a Florida street that features a physical raised curb, how should you position your vehicle''s front wheels to ensure safety?', '["Turned sharply to the left (toward the center of the road)", "Kept perfectly straight", "Turned sharply to the right (toward the curb)", "Resting completely on top of the curb"]'::jsonb, 2, 'When parking downhill with a curb, turning your wheels toward the curb ensures that if the emergency brake fails, the vehicle will roll forward into the curb and stop, preventing it from entering traffic.', 'parking', 'easy', 'drivesight-fl-11', true),
  ('FL', 'You are at a Florida intersection preparing to make a left turn. The traffic signal is a solid green circular light, but there is no green arrow. What must you do?', '["Yield the right-of-way to oncoming traffic and pedestrians, turning only when safe", "Turn immediately, as the solid green light gives you the absolute right-of-way", "Wait in the intersection until the light turns red, then quickly complete the turn", "Flash your high beams to signal oncoming traffic to stop before you turn"]'::jsonb, 0, 'A solid green light means you can proceed, but you do not have a protected turn. When turning left on a solid green, you must always yield the right-of-way to all oncoming traffic and pedestrians.', 'intersections', 'medium', 'drivesight-fl-11', true),
  ('FL', 'When passing a motorcycle traveling in the same direction on a multi-lane Florida highway, you must:', '["Share the lane with the motorcycle if there is enough physical room", "Move completely into the adjacent lane to pass, as motorcycles are entitled to the full width of their lane", "Pass the motorcycle using the right-hand shoulder if traffic is heavy", "Honk your horn continuously while passing to ensure the rider sees you"]'::jsonb, 1, 'Motorcycles have the exact same right to the full width of a traffic lane as a standard passenger vehicle. It is illegal and highly dangerous for a car to try and share a lane side-by-side with a motorcycle while passing.', 'motorcycle_awareness', 'easy', 'drivesight-fl-11', true),
  ('FL', 'In Florida, if you approach an intersection and see a pedestrian attempting to cross while carrying a white cane tipped with red, or using a guide dog, you must:', '["Tap your horn lightly to let them know a car is approaching", "Slow down to 10 mph and maneuver around them cautiously", "Come to a complete stop and yield the right-of-way, regardless of the traffic signal", "Roll down your window and offer verbal directions on when to cross safely"]'::jsonb, 2, 'Drivers must always yield the right-of-way and come to a complete stop for totally or partially blind pedestrians using a guide dog or carrying a white cane, even if the driver has a green light.', 'pedestrian_safety', 'easy', 'drivesight-fl-11', true),
  ('FL', 'When passing a slower-moving vehicle on a two-lane, two-way Florida highway, you must safely return to the right side of the road before an oncoming vehicle comes within:', '["50 feet of your vehicle", "100 feet of your vehicle", "200 feet of your vehicle", "500 feet of your vehicle"]'::jsonb, 2, 'To ensure you do not cause a head-on collision, Florida law dictates that you must complete your pass and return to your designated lane before coming within 200 feet of any approaching oncoming vehicle.', 'passing_rules', 'hard', 'drivesight-fl-11', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('FL', 'Florida', 11)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();