-- GA questions from georgia-12.json
delete from public.driving_test_questions where state_code = 'GA' and source = 'drivesight-ga-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('GA', 'Under Georgia''s ''Super Speeder'' law, a driver will face an additional $200 state fee and potential license suspension if convicted of driving at or above what speed on a two-lane road?', '["65 mph", "75 mph", "80 mph", "85 mph"]'::jsonb, 1, 'Georgia''s Super Speeder law triggers an extra $200 state fee for drivers convicted of traveling 75 mph or faster on any two-lane road, or 85 mph or faster on any road or highway in the state.', 'speed_limits', 'hard', 'drivesight-ga-12', true),
  ('GA', 'According to the Hands-Free Georgia Act, which of the following actions is legally permitted while driving a motor vehicle?', '["Holding a phone to send a quick text message while stopped at a red light", "Holding a phone to your ear, provided you are only speaking and not typing", "Using a smartphone exclusively via voice commands or a Bluetooth hands-free earpiece", "Resting the phone on your lap to watch a video while in heavy highway traffic"]'::jsonb, 2, 'The Hands-Free Georgia Act strictly prohibits drivers from having a phone in their hand or supporting it with any part of their body. You may only use a phone via earpiece, wireless, or voice-command technology.', 'distracted_driving', 'easy', 'drivesight-ga-12', true),
  ('GA', 'Georgia''s Move Over Law dictates that when approaching a stationary emergency vehicle with flashing lights on a highway, if moving over a lane is unsafe or impossible due to traffic, a driver must:', '["Maintain the posted speed limit but activate their hazard lights", "Reduce speed below the posted speed limit and be prepared to stop", "Stop completely in their current travel lane until given permission to proceed", "Honk their horn repeatedly while passing closely to warn the workers"]'::jsonb, 1, 'If it is impossible or unsafe to change lanes away from a stationary emergency vehicle in Georgia, you must reduce your speed below the posted speed limit and be prepared to stop if necessary.', 'emergency_vehicles', 'medium', 'drivesight-ga-12', true),
  ('GA', 'In Georgia, it is illegal to drive across, park in, or back up through the ''gore'' area of a highway. What specifically defines the gore area?', '["The unpaved grassy median separating opposing directions of interstate traffic", "The designated emergency pull-off zone located on steep mountain grades", "The far-left High Occupancy Vehicle (HOV) lane during restricted rush hours", "The painted triangular safety zone situated between a highway travel lane and an exit or entrance ramp"]'::jsonb, 3, 'The gore is the converging area bordered by solid white lines where an entrance or exit ramp meets the main highway. Driving across this painted triangular area is illegal and highly dangerous.', 'freeway_driving', 'medium', 'drivesight-ga-12', true),
  ('GA', 'Under what specific circumstance is it legally permissible to make a left turn at a solid red traffic light in Georgia?', '["Whenever the intersection is clear of cross traffic for at least 500 feet", "Only between the hours of Midnight and 5:00 AM", "Only when turning from a one-way street onto another one-way street, after coming to a complete stop", "Never; left turns on red are strictly prohibited statewide"]'::jsonb, 2, 'In Georgia, you may legally turn left on a solid red light only if you are turning from a one-way street onto another one-way street, provided there is no sign prohibiting it and you have made a full stop.', 'traffic_signals', 'hard', 'drivesight-ga-12', true),
  ('GA', 'When overtaking and passing a bicyclist traveling in the same direction on a Georgia road, state law mandates that a motor vehicle driver must leave a minimum safe passing distance of:', '["1 foot", "2 feet", "3 feet", "An entire traffic lane width"]'::jsonb, 2, 'Georgia''s safe passing law requires that drivers must give bicycles at least 3 feet of physical clearance when passing to prevent sideswipes and allow the cyclist room to maneuver around road hazards.', 'passing_rules', 'easy', 'drivesight-ga-12', true),
  ('GA', 'Georgia''s ''Implied Consent'' Law dictates that by operating a motor vehicle on state roads, you automatically agree to:', '["Allow police officers to search your vehicle''s trunk without a warrant during any traffic stop", "Submit to state-administered chemical tests of your blood, breath, or urine if arrested for DUI", "Carry full-coverage auto insurance instead of standard minimum liability", "Plead guilty to any moving violation cited by a State Trooper"]'::jsonb, 1, 'The Implied Consent law means that if you are lawfully arrested by an officer who suspects you of DUI, you have implicitly consented to take a chemical test of your breath, blood, or urine to determine impairment.', 'dui_alcohol_laws', 'medium', 'drivesight-ga-12', true),
  ('GA', 'A school bus has stopped on a two-lane, undivided Georgia road and is displaying its flashing red lights and an extended stop arm. You are traveling in the opposite direction. What is your legal requirement?', '["Slow down to 10 mph and pass the bus with extreme caution", "Stop your vehicle completely and remain stopped until the red lights cease flashing and the stop arm is retracted", "You are not required to stop because you are in the opposing travel lane", "Flash your high beams to warn crossing children and maintain your speed"]'::jsonb, 1, 'On a two-lane undivided highway, all traffic traveling in both directions must come to a complete stop for a school bus with flashing red lights and an extended stop arm to protect crossing children.', 'school_zones', 'easy', 'drivesight-ga-12', true),
  ('GA', 'When entering a Georgia interstate highway from an acceleration lane, who legally possesses the right-of-way?', '["The vehicle attempting to merge onto the interstate from the ramp", "Vehicles already traveling on the interstate highway", "Whichever vehicle is currently traveling at a faster rate of speed", "Commercial semi-trucks only; all passenger vehicles must yield to each other"]'::jsonb, 1, 'Vehicles currently traveling on the interstate highway have the right-of-way. The driver merging from the acceleration lane must adjust their speed and yield to find a safe gap in traffic.', 'merging', 'medium', 'drivesight-ga-12', true),
  ('GA', 'A flashing red traffic signal at a Georgia intersection must be treated legally identically to a:', '["Yield sign", "Stop sign", "Green light, assuming no cross traffic is present", "Pedestrian crosswalk warning"]'::jsonb, 1, 'A flashing red traffic light has the exact same legal meaning as a stop sign. You must come to a full and complete stop, check for pedestrians and cross traffic, and proceed only when it is safe.', 'traffic_signals', 'easy', 'drivesight-ga-12', true),
  ('GA', 'When approaching a railroad crossing in Georgia with lowered warning gates and active flashing lights, you are required to stop your vehicle within what specific distance from the nearest rail?', '["No closer than 5 feet and no further than 10 feet", "No closer than 15 feet and no further than 50 feet", "At least 100 feet away", "Only if you can physically see the train approaching the intersection"]'::jsonb, 1, 'Georgia law dictates that whenever a train is approaching and warning signals are active, a driver must stop their vehicle between 15 and 50 feet from the nearest rail of the railroad crossing.', 'railroad_crossings', 'hard', 'drivesight-ga-12', true),
  ('GA', 'To maximize visibility during inclement weather, Georgia law strictly requires drivers to activate their headlights during which of the following periods?', '["From a half-hour after sunset to a half-hour before sunrise, or when it is raining", "Only when driving on rural county roads without streetlights", "Between the hours of 8:00 PM and 5:00 AM regardless of the season", "Whenever the vehicle is traveling faster than 55 mph on the interstate"]'::jsonb, 0, 'You must use your headlights from a half-hour after sunset to a half-hour before sunrise, when it is raining, or whenever visibility is limited to less than 500 feet.', 'weather_driving', 'medium', 'drivesight-ga-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('GA', 'Georgia', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();