-- HI questions from hawaii-12.json
delete from public.driving_test_questions where state_code = 'HI' and source = 'drivesight-hi-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('HI', 'Under Hawaii''s distracted driving laws, which of the following is legally permitted while operating a motor vehicle on public roads?', '["Reading text messages as long as you do not type a reply", "Using a handheld cell phone only while stopped at a red traffic light", "Using a mobile electronic device exclusively via a hands-free system", "Holding a phone to use its GPS navigation system"]'::jsonb, 2, 'Hawaii enforces a strict hands-free law. It is completely illegal to hold or operate a mobile electronic device with your hands while driving, even when temporarily stopped at a red light or stop sign.', 'distracted_driving', 'easy', 'drivesight-hi-12', true),
  ('HI', 'You are traveling on a multi-lane Hawaii highway divided by a physical concrete median. A school bus traveling in the opposite direction stops and extends its red flashing lights. What must you do?', '["Come to a complete stop and wait for the bus to retract its stop arm", "Slow to 15 mph and proceed with extreme caution", "You may continue driving without stopping because of the physical median", "Honk your horn to warn pedestrians but maintain your speed"]'::jsonb, 2, 'In Hawaii, if a highway is divided by an intervening space or a physical barrier (like a concrete median), vehicles traveling in the opposite direction of a stopped school bus are not required to stop.', 'school_zones', 'medium', 'drivesight-hi-12', true),
  ('HI', 'Hawaii''s ''Zero Tolerance'' law for underage drinking and driving means that a driver under the age of 21 can face license suspension for a Blood Alcohol Concentration (BAC) of:', '["0.08% or higher", "0.05% or higher", "0.02% or higher", "0.10% or higher"]'::jsonb, 2, 'Hawaii enforces a Zero Tolerance law for drivers under 21. Operating a vehicle with a measurable BAC of 0.02% or greater will result in severe penalties, including license suspension.', 'dui_alcohol_laws', 'medium', 'drivesight-hi-12', true),
  ('HI', 'To maximize visibility during dark or hazardous conditions, Hawaii law requires you to turn on your vehicle''s headlights during what specific timeframe?', '["From one hour after sunset until one hour before sunrise", "From a half-hour after sunset to a half-hour before sunrise", "From 8:00 PM to 6:00 AM regardless of the season", "Only when streetlights are not present on the roadway"]'::jsonb, 1, 'State law mandates that headlights must be activated from 30 minutes after sunset until 30 minutes before sunrise, or at any other time when visibility is reduced to less than 500 feet.', 'weather_driving', 'easy', 'drivesight-hi-12', true),
  ('HI', 'You approach an uncontrolled four-way intersection at the same time as a vehicle directly across from you. You intend to turn left, while the other vehicle is traveling straight through. Who has the right-of-way?', '["You have the right-of-way because you are turning", "The vehicle traveling straight has the right-of-way", "The vehicle that is traveling at a higher rate of speed", "Whichever vehicle is larger and heavier"]'::jsonb, 1, 'When two vehicles approach an intersection from opposite directions at the same time, a driver turning left must always yield the right-of-way to the vehicle traveling straight through.', 'right_of_way', 'medium', 'drivesight-hi-12', true),
  ('HI', 'When parallel parking your vehicle facing downhill on a street in Honolulu that has a raised curb, how should you position your front wheels?', '["Keep them straight parallel to the roadway", "Turn them sharply to the right, toward the curb", "Turn them sharply to the left, toward the center of the road", "Rest the tires directly on top of the curb"]'::jsonb, 1, 'When parked facing downhill next to a curb, you should always turn your front wheels sharply toward the right (toward the curb). If your brakes fail, the vehicle will roll into the curb and stop.', 'parking', 'easy', 'drivesight-hi-12', true),
  ('HI', 'A solid yellow line next to a broken yellow line running down the center of a two-way Hawaii roadway indicates that passing is:', '["Prohibited for both directions of traffic", "Permitted only for the side with the solid yellow line", "Permitted only for the side with the broken yellow line", "Permitted during daylight hours for both sides"]'::jsonb, 2, 'A solid yellow line paired with a broken yellow line means that vehicles traveling adjacent to the broken line are permitted to cross it to pass, while vehicles on the solid line side are prohibited from passing.', 'lane_changes', 'easy', 'drivesight-hi-12', true),
  ('HI', 'If you approach a crosswalk and notice a pedestrian who is completely or partially blind, identified by carrying a white cane or using a guide dog, what must you do?', '["Honk your horn to warn them before driving around them", "Yield the right-of-way and come to a full stop until they have crossed", "Slow down to 10 mph and proceed with extreme caution", "Roll down your window and give verbal directions to the pedestrian"]'::jsonb, 1, 'Hawaii drivers must always yield the right-of-way and come to a complete stop for pedestrians carrying a white cane or using a guide dog, regardless of traffic signals or crosswalk markings.', 'pedestrian_safety', 'easy', 'drivesight-hi-12', true),
  ('HI', 'When approaching an intersection displaying a flashing red traffic light, Hawaii drivers must treat it legally the same as:', '["A yield sign", "A standard stop sign", "A pedestrian crossing zone warning", "A flashing yellow light"]'::jsonb, 1, 'A flashing red traffic signal carries the identical legal requirement as a stop sign. You must come to a complete stop behind the limit line, yield to traffic, and proceed only when safe.', 'traffic_signals', 'easy', 'drivesight-hi-12', true),
  ('HI', 'While traveling on the H-1 freeway, you realize you have just missed your intended exit. Your safest and legal action is to:', '["Carefully back up along the right shoulder with your hazard lights flashing", "Stop in the right lane and wait for an opening to reverse", "Continue driving to the next available exit and safely turn around", "Make a U-turn through the grassy median separating the highway"]'::jsonb, 2, 'Backing up or making U-turns on an interstate freeway is extremely dangerous and strictly illegal. If you miss your exit, you must always proceed to the next available exit.', 'freeway_driving', 'easy', 'drivesight-hi-12', true),
  ('HI', 'When preparing to merge onto a Hawaii freeway from an acceleration lane, who holds the legal right-of-way?', '["The vehicle attempting to merge from the entrance ramp", "The vehicles currently traveling on the freeway", "The larger of the two interacting vehicles", "Vehicles traveling in the far-left passing lane"]'::jsonb, 1, 'Drivers entering a freeway from an acceleration lane must yield the right-of-way to vehicles already traveling on the mainline of the freeway.', 'merging', 'medium', 'drivesight-hi-12', true),
  ('HI', 'To maintain a safe following distance behind the vehicle ahead of you under normal driving conditions, the Hawaii Driver''s Manual recommends using the:', '["One car length for every 10 mph rule", "Three-second rule", "Two-second rule", "Five-second rule"]'::jsonb, 1, 'Hawaii recommends the three-second rule to maintain a safe following distance under ideal conditions. You should increase this distance during bad weather or when following motorcycles.', 'defensive_driving', 'easy', 'drivesight-hi-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('HI', 'Hawaii', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();