-- IL questions from illinois-12.json
delete from public.driving_test_questions where state_code = 'IL' and source = 'drivesight-il-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('IL', 'Under Illinois'' ''Scott''s Law'' (the Move Over Law), what must you do when approaching any stationary vehicle displaying flashing lights on the side of a multi-lane highway?', '["Honk your horn to let the driver know you are passing", "Maintain your speed but turn on your hazard lights", "Reduce your speed significantly and change lanes away from the stationary vehicle if it is safe to do so", "Come to a complete stop and wait for a police officer to wave you around"]'::jsonb, 2, 'Scott''s Law in Illinois requires drivers approaching ANY stationary vehicle with flashing hazard lights (including passenger cars, tow trucks, and police) to slow down, proceed with caution, and change lanes away from the vehicle if possible.', 'emergency_vehicles', 'medium', 'drivesight-il-12', true),
  ('IL', 'Unless otherwise posted, what is the strict maximum speed limit in an Illinois school zone on school days between the hours of 7:00 a.m. and 4:00 p.m. when children are present?', '["15 mph", "20 mph", "25 mph", "30 mph"]'::jsonb, 1, 'In Illinois, the mandated speed limit in a designated school zone is 20 miles per hour on school days when children are actively present. Fines for violating this are severely increased.', 'school_zones', 'easy', 'drivesight-il-12', true),
  ('IL', 'You are driving on a four-lane Illinois highway (two lanes in each direction) separated only by a painted double yellow line. A school bus traveling in the opposite direction stops and extends its red flashing lights. What is your legal obligation?', '["Stop immediately; all traffic on undivided highways must stop", "Slow down to 10 mph and pass cautiously", "You are not required to stop if you are traveling in the opposite direction on a road with four or more lanes", "Stop only if the crossing arm physically blocks your travel lane"]'::jsonb, 2, 'In Illinois, if you are traveling on a highway with four or more lanes, you do not need to stop for a school bus traveling in the opposite direction, even if the road is undivided. Only traffic behind the bus must stop.', 'school_zones', 'hard', 'drivesight-il-12', true),
  ('IL', 'Illinois enforces a ''Zero Tolerance'' law regarding underage drinking and driving. If a driver under the age of 21 is stopped and tests positive for any trace of alcohol in their system, their license will be automatically suspended for a minimum of:', '["30 days", "3 months", "6 months", "1 year"]'::jsonb, 2, 'Under the Zero Tolerance Law, if a driver under 21 is caught with any trace of alcohol in their system, their driving privileges will automatically be suspended for a minimum of 6 months for a first offense.', 'dui_alcohol_laws', 'hard', 'drivesight-il-12', true),
  ('IL', 'According to the Illinois distracted driving laws, under what condition is it legally permissible for a driver of any age to text while driving?', '["Only when stopped at a solid red traffic light", "Only when utilizing voice-activated, hands-free technology", "If the phone is kept below the dashboard out of the driver''s direct line of sight", "Never, texting is universally banned even with voice commands"]'::jsonb, 1, 'Illinois law strictly prohibits the use of hand-held cell phones, texting, or using other electronic communications while operating a motor vehicle. You may only text if you are using voice-activated, entirely hands-free technology.', 'distracted_driving', 'medium', 'drivesight-il-12', true),
  ('IL', 'When preparing to execute a legal left turn on a solid red light in Illinois, you must first come to a complete stop and yield. Under what specific condition is this turn allowed?', '["When turning from a two-way street onto another two-way street", "When turning from a one-way street onto another one-way street", "When turning from a two-way street onto a one-way street", "Whenever the intersection is completely clear of cross traffic"]'::jsonb, 1, 'In Illinois, turning left on a solid red light is highly restricted. It is only legal when you are turning from a one-way street directly onto another one-way street that has traffic moving to the left.', 'traffic_signals', 'medium', 'drivesight-il-12', true),
  ('IL', 'When passing a bicyclist who is traveling in the same direction on an Illinois road, state law dictates that a motor vehicle must leave a minimum physical clearance of at least:', '["2 feet", "3 feet", "4 feet", "5 feet"]'::jsonb, 1, 'Illinois'' safe passing law requires drivers to provide a minimum of 3 feet of space when passing a bicyclist, and the driver must not return to the right side of the lane until safely clear.', 'passing_rules', 'easy', 'drivesight-il-12', true),
  ('IL', 'To increase visibility and safety during inclement weather, Illinois state law requires that you turn on your vehicle''s headlights whenever:', '["You are traveling on an interstate highway", "The temperature falls below freezing", "You must use your windshield wipers due to rain, snow, or fog", "You enter a marked construction or work zone"]'::jsonb, 2, 'Illinois law explicitly mandates that a driver must turn on their headlights any time atmospheric conditions require the use of their windshield wipers to maintain visibility.', 'weather_driving', 'easy', 'drivesight-il-12', true),
  ('IL', 'You are parking your vehicle facing uphill on a steep street in Chicago that features a prominent concrete curb. To secure your vehicle against rolling into traffic, your front wheels should be turned:', '["Sharply to the left, away from the curb", "Sharply to the right, toward the curb", "Parallel to the centerline of the roadway", "Directly onto the sidewalk"]'::jsonb, 0, 'When parking uphill with a curb, turn your front wheels sharply away from the curb. This ensures that if the vehicle begins to roll backward, the back of the front tire will hit the curb and stop the car.', 'parking', 'medium', 'drivesight-il-12', true),
  ('IL', 'At a four-way stop intersection in Illinois, three vehicles arrive simultaneously. Which vehicle legally holds the right-of-way?', '["The vehicle traveling at the fastest speed", "The vehicle making a left-hand turn", "The vehicle positioned furthest to the right", "The vehicle making a right-hand turn"]'::jsonb, 2, 'At an intersection controlled by four-way stop signs where multiple vehicles arrive at the same time, the driver of the vehicle on the left must yield the right-of-way to the vehicle on the immediate right.', 'right_of_way', 'easy', 'drivesight-il-12', true),
  ('IL', 'If you approach a railroad crossing in Illinois that does not have warning lights or lowered crossing gates, what is your safest and legal course of action?', '["Accelerate to clear the tracks as quickly as possible", "Slow down, look in both directions along the tracks, and listen for an approaching train before crossing", "Stop completely at the tracks regardless of whether a train is visible", "Shift gears manually while crossing the tracks"]'::jsonb, 1, 'At passive railroad crossings (those without active gates or flashing lights), it is the driver''s responsibility to slow down, look both ways, and listen carefully for a train before proceeding across the tracks.', 'railroad_crossings', 'easy', 'drivesight-il-12', true),
  ('IL', 'When entering an Illinois interstate from an acceleration lane, your primary responsibility to ensure a safe merge is to:', '["Come to a full stop at the end of the ramp and wait for an opening", "Drive down the shoulder until traffic slows down enough to let you in", "Adjust your speed to match the flow of highway traffic and yield to vehicles already on the interstate", "Signal continuously, forcing drivers in the right lane to move to the left lane"]'::jsonb, 2, 'Drivers entering a highway from an acceleration lane must yield the right-of-way to vehicles already traveling on the mainline. You must adjust your speed to find a safe gap in the traffic flow.', 'merging', 'medium', 'drivesight-il-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('IL', 'Illinois', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();