-- IN questions from indiana-12.json
delete from public.driving_test_questions where state_code = 'IN' and source = 'drivesight-in-12';
insert into public.driving_test_questions (state_code, prompt, choices, answer_index, explanation, category, difficulty, source, is_active)
values
  ('IN', 'Indiana''s Move Over Law applies to stationary emergency, maintenance, and utility vehicles displaying flashing lights. If you cannot safely change lanes to move away from the vehicle, you must:', '["Stop completely until an officer directs you to proceed", "Maintain your speed but turn on your hazard lights", "Reduce your speed to at least 10 mph below the posted speed limit and proceed with caution", "Accelerate quickly to clear the hazard zone"]'::jsonb, 2, 'If it is impossible or unsafe to change lanes away from a stationary emergency or recovery vehicle in Indiana, the law requires you to slow down to at least 10 mph below the posted speed limit and proceed with caution.', 'emergency_vehicles', 'medium', 'drivesight-in-12', true),
  ('IN', 'Under Indiana law, what is the maximum statutory speed limit on a rural interstate highway unless otherwise posted?', '["60 mph", "65 mph", "70 mph", "75 mph"]'::jsonb, 2, 'In Indiana, passenger vehicles may travel at a maximum speed of 70 mph on rural interstate highways, provided weather and traffic conditions allow for safe driving at that speed.', 'speed_limits', 'medium', 'drivesight-in-12', true),
  ('IN', 'A school bus has stopped on an undivided, two-lane road in Indiana and activated its flashing red lights. You are traveling in the opposite direction. Are you required to stop?', '["Yes, all traffic traveling in both directions must stop", "No, only vehicles traveling in the same direction as the bus must stop", "Yes, but you may proceed at 10 mph after yielding to children", "No, unless a crossing guard is physically standing in the roadway"]'::jsonb, 0, 'On a two-lane undivided roadway, Indiana law requires that all vehicles traveling in both directions must come to a complete stop for a school bus displaying its flashing red lights.', 'school_zones', 'easy', 'drivesight-in-12', true),
  ('IN', 'For drivers under the age of 18 in Indiana, what are the legal restrictions regarding the use of telecommunications devices while driving?', '["They may use a cell phone only if it is completely hands-free", "They may text only when stopped at a red light", "They are strictly prohibited from using any telecommunications device, including hands-free, except to call 911", "They may use a handheld phone for phone calls but not for texting"]'::jsonb, 2, 'Drivers under 18 in Indiana are banned from using any type of telecommunications device while driving, even if the device is hands-free or Bluetooth enabled, unless they are making a genuine emergency 911 call.', 'distracted_driving', 'medium', 'drivesight-in-12', true),
  ('IN', 'To maintain a safe following distance under ideal driving conditions, the Indiana Driver''s Manual recommends drivers follow the:', '["One car length per 10 mph rule", "Two to three-second rule", "Five-second rule", "100-foot constant distance rule"]'::jsonb, 1, 'Indiana recommends using the two to three-second rule to maintain a safe following distance under normal, dry driving conditions. This distance should be increased during bad weather or when following large trucks.', 'defensive_driving', 'easy', 'drivesight-in-12', true),
  ('IN', 'When preparing to make a right turn at an intersection with a solid red traffic light in Indiana, what is the proper legal procedure?', '["Slow down, look both ways, and turn without fully stopping if the road is clear", "Come to a full and complete stop, yield the right-of-way to pedestrians and oncoming traffic, then proceed when safe", "Wait for the pedestrian countdown timer to end, then turn", "You cannot turn right on a solid red light in Indiana under any circumstances"]'::jsonb, 1, 'Unless specifically prohibited by a sign, you may make a right turn on red in Indiana, but you must first bring your vehicle to a full and complete stop and yield to all cross traffic and pedestrians.', 'traffic_signals', 'easy', 'drivesight-in-12', true),
  ('IN', 'When approaching a railroad crossing where active red lights are flashing, Indiana law requires you to stop your vehicle within what distance of the nearest rail?', '["No closer than 15 feet and no further than 50 feet", "No closer than 5 feet and no further than 20 feet", "Exactly 30 feet away", "Only if the physical crossing gate is fully lowered across your lane"]'::jsonb, 0, 'When a train is approaching and railroad crossing signals are active, Indiana state law dictates that a driver must come to a complete stop between 15 and 50 feet from the nearest rail.', 'railroad_crossings', 'hard', 'drivesight-in-12', true),
  ('IN', 'You are driving on a multi-lane highway in Indiana and wish to pass a large commercial semi-truck. Why should you avoid lingering in the lanes directly beside the truck?', '["Semi-trucks create a vacuum that can pull your car into their lane", "The areas directly beside a semi-truck are large blind spots known as ''No-Zones''", "Truck drivers are required by law to change lanes frequently", "You are required to honk your horn continuously when beside a commercial vehicle"]'::jsonb, 1, 'Commercial trucks have extensive blind spots on both sides, the immediate rear, and the front. These are called ''No-Zones.'' If you linger in these areas, the truck driver cannot see you, making a collision highly likely.', 'defensive_driving', 'easy', 'drivesight-in-12', true),
  ('IN', 'If your vehicle begins to hydroplane on a wet Indiana roadway during a heavy rainstorm, what is the safest way to regain control of the vehicle?', '["Slam on the brakes to force the tires back onto the pavement", "Jerk the steering wheel sharply in the opposite direction of the skid", "Ease your foot off the accelerator pedal and steer straight until the tires regain traction", "Accelerate quickly to push the water out from beneath the tires"]'::jsonb, 2, 'During a hydroplane, sudden braking or steering can cause a total loss of control. The best action is to take your foot off the gas and keep the wheel straight, allowing the vehicle to slow naturally until the tires reconnect with the road.', 'weather_driving', 'medium', 'drivesight-in-12', true),
  ('IN', 'In Indiana, state law considers a non-commercial driver over the age of 21 to be legally intoxicated and subject to a DUI arrest if their Blood Alcohol Concentration (BAC) reaches or exceeds:', '["0.04%", "0.05%", "0.08%", "0.10%"]'::jsonb, 2, 'For standard drivers aged 21 and older in Indiana, driving with a BAC of 0.08% or higher constitutes driving under the influence and will result in criminal charges and license suspension.', 'dui_alcohol_laws', 'easy', 'drivesight-in-12', true),
  ('IN', 'When preparing to enter an Indiana roundabout intersection, which traffic legally holds the right-of-way?', '["Traffic that is attempting to enter the roundabout from the right", "Traffic that is already actively circulating inside the roundabout", "Whichever vehicle arrives at the intersection first", "Traffic attempting to exit the roundabout"]'::jsonb, 1, 'Drivers attempting to enter a roundabout must always yield the right-of-way to vehicles, bicyclists, and pedestrians that are already circulating within the traffic circle.', 'intersections', 'easy', 'drivesight-in-12', true),
  ('IN', 'A solid double yellow line running down the center of an Indiana roadway indicates that:', '["Passing is strictly prohibited for traffic traveling in both directions", "Passing is allowed if the vehicle ahead is moving significantly below the speed limit", "The road is transitioning into a one-way street", "The lane is designated for carpool vehicles only"]'::jsonb, 0, 'A solid double yellow line separates traffic moving in opposite directions and means that neither lane is legally permitted to cross the centerline to overtake and pass another vehicle.', 'lane_changes', 'easy', 'drivesight-in-12', true);
insert into public.state_driving_tests (state_code, state_name, question_count)
values ('IN', 'Indiana', 12)
on conflict (state_code) do update set
  question_count = excluded.question_count,
  updated_at = now();