-- Insert US States
INSERT INTO states (name, abbreviation) VALUES
('Alabama', 'AL'),
('Alaska', 'AK'),
('Arizona', 'AZ'),
('Arkansas', 'AR'),
('California', 'CA'),
('Colorado', 'CO'),
('Connecticut', 'CT'),
('Delaware', 'DE'),
('Florida', 'FL'),
('Georgia', 'GA'),
('Hawaii', 'HI'),
('Idaho', 'ID'),
('Illinois', 'IL'),
('Indiana', 'IN'),
('Iowa', 'IA'),
('Kansas', 'KS'),
('Kentucky', 'KY'),
('Louisiana', 'LA'),
('Maine', 'ME'),
('Maryland', 'MD'),
('Massachusetts', 'MA'),
('Michigan', 'MI'),
('Minnesota', 'MN'),
('Mississippi', 'MS'),
('Missouri', 'MO'),
('Montana', 'MT'),
('Nebraska', 'NE'),
('Nevada', 'NV'),
('New Hampshire', 'NH'),
('New Jersey', 'NJ'),
('New Mexico', 'NM'),
('New York', 'NY'),
('North Carolina', 'NC'),
('North Dakota', 'ND'),
('Ohio', 'OH'),
('Oklahoma', 'OK'),
('Oregon', 'OR'),
('Pennsylvania', 'PA'),
('Rhode Island', 'RI'),
('South Carolina', 'SC'),
('South Dakota', 'SD'),
('Tennessee', 'TN'),
('Texas', 'TX'),
('Utah', 'UT'),
('Vermont', 'VT'),
('Virginia', 'VA'),
('Washington', 'WA'),
('West Virginia', 'WV'),
('Wisconsin', 'WI'),
('Wyoming', 'WY');

-- Insert sample signs
INSERT INTO signs (name, mutcd_code, category, description, penalties) VALUES
('Stop Sign', 'R1-1', 'Regulatory', 'Indicates a complete stop is required. Drivers must come to a full stop at the stop line and yield to other traffic.', 'Fines ranging from $100-$500 and points on driving record'),
('Yield Sign', 'R1-2', 'Regulatory', 'Indicates drivers must slow down and be prepared to stop if necessary to yield the right-of-way to other traffic.', 'Fines ranging from $75-$300 and possible points'),
('Speed Limit 25', 'R2-1', 'Regulatory', 'Indicates the maximum speed at which vehicles may legally travel on the road.', 'Fines of $50-$200 per 5 mph over limit'),
('No Entry', 'R5-1', 'Regulatory', 'Prohibits entry to a roadway or area. Usually at one-way streets or restricted areas.', 'Fines and possible towing'),
('Warning', 'W1-1', 'Warning', 'Warns drivers of potential hazards or changes in road conditions ahead.', 'No direct penalty, but violations based on resulting accidents'),
('Pedestrian Crossing', 'W11-2', 'Warning', 'Warns drivers that they are approaching an area where pedestrians frequently cross.', 'Fines if pedestrian is hit due to driver negligence'),
('School Zone', 'S4-1', 'School', 'Indicates a school zone with reduced speed limits. Usually 15-25 mph during school hours.', 'Double fines in school zones'),
('One Way', 'R6-1', 'Regulatory', 'Indicates traffic flow direction on a one-way street.', 'Fines and points for driving wrong way');
