"""Build unified SQL for Supabase deploy: schema.sql, seed.sql, and migrations."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "supabase" / "schema" / "base.sql"
SEEDS_DIR = ROOT / "supabase" / "seeds"
SCHEMA_OUT = ROOT / "supabase" / "schema.sql"
SEED_OUT = ROOT / "supabase" / "seed.sql"
MIGRATION_OUT = ROOT / "supabase" / "migrations" / "20250522100000_question_seeds.sql"

HEADER = """-- ---------------------------------------------------------------------------
-- AUTO-GENERATED by: npm run db:build
-- Do not edit this file by hand. Edit supabase/schema/base.sql and supabase/seeds/*.sql
-- ---------------------------------------------------------------------------

"""

FOOTER = """
-- ---------------------------------------------------------------------------
-- Sync per-state question_count from active rows in driving_test_questions
-- ---------------------------------------------------------------------------

select public.sync_state_question_counts();
"""


def read_seed_files() -> list[tuple[str, str]]:
    files = sorted(SEEDS_DIR.glob("*.sql"))
    if not files:
        raise SystemExit(f"No seed SQL files found in {SEEDS_DIR}")
    return [(path.name, path.read_text(encoding="utf-8").strip()) for path in files]


def wrap_seeds(seeds: list[tuple[str, str]]) -> str:
    parts: list[str] = []
    for name, body in seeds:
        parts.append(f"-- >>> supabase/seeds/{name}\n{body}\n")
    return "\n".join(parts)


def main() -> None:
    if not BASE.exists():
        raise SystemExit(f"Missing base schema: {BASE}")

    base = BASE.read_text(encoding="utf-8").strip()
    seeds = read_seed_files()
    seed_block = wrap_seeds(seeds)

    SCHEMA_OUT.write_text(
        HEADER + base + "\n\n" + seed_block + FOOTER,
        encoding="utf-8",
    )

    SEED_OUT.write_text(
        HEADER
        + "-- Requires tables from supabase/schema/base.sql (or migrations) first.\n\n"
        + seed_block
        + FOOTER,
        encoding="utf-8",
    )

    MIGRATION_OUT.write_text(
        HEADER
        + "-- Question bank seeds (safe to re-run: each file deletes by source id first)\n\n"
        + seed_block
        + FOOTER,
        encoding="utf-8",
    )

    print(f"Built {SCHEMA_OUT.relative_to(ROOT)}")
    print(f"Built {SEED_OUT.relative_to(ROOT)}")
    print(f"Built {MIGRATION_OUT.relative_to(ROOT)}")
    print(f"Included {len(seeds)} seed file(s): {', '.join(name for name, _ in seeds)}")


if __name__ == "__main__":
    main()
